# _config.yml
title: Mi Sitio Jekyll
description: Este es un sitio de ejemplo utilizando Jekyll.
baseurl: "" 
url: "https://valensoto486.github.io/TallerPlataformas/" 

# Configuración de temas
theme: minima

# Otros ajustes 
markdown: kramdown
